/**
 * POST /auth/upgrade — Guest-to-registered account upgrade (AUTH-05)
 *
 * Converts a guest session to a registered account. Validates the guest JWT
 * from the session cookie, creates a new accounts row, and replaces the
 * session cookie in-place with a 30-day registered cookie (D-06).
 *
 * Requires: valid guest JWT in session cookie (isGuest: true)
 * Returns: { userId: newUserId, isGuest: false, displayName } + new 30-day cookie
 *
 * If JWT missing or not a guest token: 401
 * If email already taken: 409 { error: 'email_taken' }
 *
 * Security coverage:
 *   - T-02-18: jwtVerify() + isGuest===true guard prevents unauthorized upgrade
 *   - T-02-16: bcrypt.hash(cost:12) — raw password never stored
 *   - SEC-05: HttpOnly cookie via issueRegisteredCookie (lib/cookies.ts)
 *
 * All JWT signing via lib/auth.ts; all cookie ops via lib/cookies.ts (Pattern I).
 */
import type { FastifyInstance } from 'fastify'
import bcrypt from 'bcryptjs'
import { RegisterSchema } from '@game/shared'
import { db } from '../../db/client.js'
import { accounts } from '../../db/schema.js'
import { signRegisteredJwt } from '../../lib/auth.js'
import { issueRegisteredCookie } from '../../lib/cookies.js'

/**
 * Returns true if the error is a PostgreSQL unique constraint violation (code 23505).
 * Drizzle wraps the original PostgresError as a DrizzleQueryError with err.cause = PostgresError.
 */
function isUniqueViolation(err: unknown): boolean {
  if (typeof err !== 'object' || err === null) return false
  const e = err as Record<string, unknown>
  if (e['code'] === '23505') return true
  if (typeof e['cause'] === 'object' && e['cause'] !== null) {
    const cause = e['cause'] as Record<string, unknown>
    if (cause['code'] === '23505') return true
  }
  return false
}

// JWT payload shape from @fastify/jwt — declared via module augmentation
declare module '@fastify/jwt' {
  interface FastifyJWT {
    payload: { userId: string; isGuest: boolean; role: string; displayName?: string }
    user: { userId: string; isGuest: boolean; role: string; displayName?: string }
  }
}

export default async function upgradeRoute(app: FastifyInstance): Promise<void> {
  app.post('/auth/upgrade', async (request, reply) => {
    // Verify JWT from session cookie — return 401 if missing or invalid
    try {
      await request.jwtVerify()
    } catch {
      return reply.code(401).send({ error: 'unauthorized' })
    }

    // Only guest tokens can be upgraded (T-02-18 mitigate)
    if (!request.user.isGuest) {
      return reply.code(401).send({ error: 'unauthorized' })
    }

    // Zod validation on body
    const parsed = RegisterSchema.safeParse(request.body)
    if (!parsed.success) {
      return reply.code(400).send({ error: 'validation_failed', issues: parsed.error.issues })
    }

    const { email, password } = parsed.data

    // Hash password with cost factor 12 (T-02-16 mitigate)
    const passwordHash = await bcrypt.hash(password, 12)

    // displayName: first part of email before @, trimmed, lowercase, max 20 chars
    const displayName = email.split('@')[0].slice(0, 20).toLowerCase()

    // Insert new account row — guest UUID is discarded; new UUID generated by defaultRandom()
    let row: { id: string; displayName: string }
    try {
      const inserted = await db
        .insert(accounts)
        .values({ email, passwordHash, displayName })
        .returning({ id: accounts.id, displayName: accounts.displayName })
      row = inserted[0]
    } catch (err: unknown) {
      // Drizzle wraps PostgresError as DrizzleQueryError — check err.cause.code
      // for the original PostgreSQL error code (23505 = unique constraint violation)
      if (isUniqueViolation(err)) {
        return reply.code(409).send({ error: 'email_taken' })
      }
      throw err
    }

    // Sign new registered JWT and replace session cookie in-place (D-06)
    const token = signRegisteredJwt(app, row.id)
    issueRegisteredCookie(reply, token)

    return reply.code(200).send({ userId: row.id, isGuest: false, displayName: row.displayName })
  })
}
